// jqwidgets-ver5.2.0/jqwidgets-ts/angular_jqxcalendar.ts
/*
jQWidgets v5.2.0 (2017-Sep)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges, ChangeDetectionStrategy } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

const noop = () => { };
declare let JQXLite: any;

export const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR: any = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => jqxCalendarComponent),
    multi: true
}

@Component({
    selector: 'jqxCalendar',
    template: '<div><ng-content></ng-content></div>',
    providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR],
    changeDetection: ChangeDetectionStrategy.OnPush
})

export class jqxCalendarComponent implements ControlValueAccessor, OnChanges 
{
   @Input('backText') attrBackText: any;
   @Input('columnHeaderHeight') attrColumnHeaderHeight: any;
   @Input('clearString') attrClearString: any;
   @Input('culture') attrCulture: any;
   @Input('dayNameFormat') attrDayNameFormat: any;
   @Input('disabled') attrDisabled: any;
   @Input('enableWeekend') attrEnableWeekend: any;
   @Input('enableViews') attrEnableViews: any;
   @Input('enableOtherMonthDays') attrEnableOtherMonthDays: any;
   @Input('enableFastNavigation') attrEnableFastNavigation: any;
   @Input('enableHover') attrEnableHover: any;
   @Input('enableAutoNavigation') attrEnableAutoNavigation: any;
   @Input('enableTooltips') attrEnableTooltips: any;
   @Input('forwardText') attrForwardText: any;
   @Input('firstDayOfWeek') attrFirstDayOfWeek: any;
   @Input('min') attrMin: any;
   @Input('max') attrMax: any;
   @Input('navigationDelay') attrNavigationDelay: any;
   @Input('rowHeaderWidth') attrRowHeaderWidth: any;
   @Input('readOnly') attrReadOnly: any;
   @Input('restrictedDates') attrRestrictedDates: any;
   @Input('rtl') attrRtl: any;
   @Input('stepMonths') attrStepMonths: any;
   @Input('showWeekNumbers') attrShowWeekNumbers: any;
   @Input('showDayNames') attrShowDayNames: any;
   @Input('showOtherMonthDays') attrShowOtherMonthDays: any;
   @Input('showFooter') attrShowFooter: any;
   @Input('selectionMode') attrSelectionMode: any;
   @Input('specialDates') attrSpecialDates: any;
   @Input('theme') attrTheme: any;
   @Input('titleHeight') attrTitleHeight: any;
   @Input('titleFormat') attrTitleFormat: any;
   @Input('todayString') attrTodayString: any;
   @Input('value') attrValue: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['backText','columnHeaderHeight','clearString','culture','dayNameFormat','disabled','enableWeekend','enableViews','enableOtherMonthDays','enableFastNavigation','enableHover','enableAutoNavigation','enableTooltips','forwardText','firstDayOfWeek','height','min','max','navigationDelay','rowHeaderWidth','readOnly','restrictedDates','rtl','stepMonths','showWeekNumbers','showDayNames','showOtherMonthDays','showFooter','selectionMode','specialDates','theme','titleHeight','titleFormat','todayString','value','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxCalendar;

   private onTouchedCallback: () => void = noop;
   private onChangeCallback: (_: any) => void = noop;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxCalendar(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxCalendar(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxCalendar(this.properties[i])) {
                  this.host.jqxCalendar(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void {
      let classes: any = parentEl.classList;
      childEl.classList.add(...classes);
      parentEl.className = '';
   }

   moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void {
      let style = parentEl.style.cssText;
      childEl.style.cssText = style
      parentEl.style.cssText = '';
   }

   createComponent(options?: any): void {
      if (options) {
         JQXLite.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = JQXLite(this.elementRef.nativeElement.firstChild);

      this.moveClasses(this.elementRef.nativeElement, this.host[0]);
      this.moveStyles(this.elementRef.nativeElement, this.host[0]);

      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxCalendar', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   writeValue(value: any): void {
       if(this.widgetObject) {
           this.onChangeCallback(this.host.val());
       }
   }

   registerOnChange(fn: any): void {
       this.onChangeCallback = fn;
   }

   registerOnTouched(fn: any): void {
       this.onTouchedCallback = fn;
   }

   setOptions(options: any) : void {
      this.host.jqxCalendar('setOptions', options);
   }

   // jqxCalendarComponent properties
   backText(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('backText', arg);
      } else {
          return this.host.jqxCalendar('backText');
      }
   }

   columnHeaderHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('columnHeaderHeight', arg);
      } else {
          return this.host.jqxCalendar('columnHeaderHeight');
      }
   }

   clearString(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('clearString', arg);
      } else {
          return this.host.jqxCalendar('clearString');
      }
   }

   culture(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('culture', arg);
      } else {
          return this.host.jqxCalendar('culture');
      }
   }

   dayNameFormat(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('dayNameFormat', arg);
      } else {
          return this.host.jqxCalendar('dayNameFormat');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('disabled', arg);
      } else {
          return this.host.jqxCalendar('disabled');
      }
   }

   enableWeekend(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableWeekend', arg);
      } else {
          return this.host.jqxCalendar('enableWeekend');
      }
   }

   enableViews(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableViews', arg);
      } else {
          return this.host.jqxCalendar('enableViews');
      }
   }

   enableOtherMonthDays(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableOtherMonthDays', arg);
      } else {
          return this.host.jqxCalendar('enableOtherMonthDays');
      }
   }

   enableFastNavigation(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableFastNavigation', arg);
      } else {
          return this.host.jqxCalendar('enableFastNavigation');
      }
   }

   enableHover(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableHover', arg);
      } else {
          return this.host.jqxCalendar('enableHover');
      }
   }

   enableAutoNavigation(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableAutoNavigation', arg);
      } else {
          return this.host.jqxCalendar('enableAutoNavigation');
      }
   }

   enableTooltips(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableTooltips', arg);
      } else {
          return this.host.jqxCalendar('enableTooltips');
      }
   }

   forwardText(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('forwardText', arg);
      } else {
          return this.host.jqxCalendar('forwardText');
      }
   }

   firstDayOfWeek(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('firstDayOfWeek', arg);
      } else {
          return this.host.jqxCalendar('firstDayOfWeek');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('height', arg);
      } else {
          return this.host.jqxCalendar('height');
      }
   }

   min(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('min', arg);
      } else {
          return this.host.jqxCalendar('min');
      }
   }

   max(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('max', arg);
      } else {
          return this.host.jqxCalendar('max');
      }
   }

   navigationDelay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('navigationDelay', arg);
      } else {
          return this.host.jqxCalendar('navigationDelay');
      }
   }

   rowHeaderWidth(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('rowHeaderWidth', arg);
      } else {
          return this.host.jqxCalendar('rowHeaderWidth');
      }
   }

   readOnly(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('readOnly', arg);
      } else {
          return this.host.jqxCalendar('readOnly');
      }
   }

   restrictedDates(arg?: Array<Date>) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('restrictedDates', arg);
      } else {
          return this.host.jqxCalendar('restrictedDates');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('rtl', arg);
      } else {
          return this.host.jqxCalendar('rtl');
      }
   }

   stepMonths(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('stepMonths', arg);
      } else {
          return this.host.jqxCalendar('stepMonths');
      }
   }

   showWeekNumbers(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('showWeekNumbers', arg);
      } else {
          return this.host.jqxCalendar('showWeekNumbers');
      }
   }

   showDayNames(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('showDayNames', arg);
      } else {
          return this.host.jqxCalendar('showDayNames');
      }
   }

   showOtherMonthDays(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('showOtherMonthDays', arg);
      } else {
          return this.host.jqxCalendar('showOtherMonthDays');
      }
   }

   showFooter(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('showFooter', arg);
      } else {
          return this.host.jqxCalendar('showFooter');
      }
   }

   selectionMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('selectionMode', arg);
      } else {
          return this.host.jqxCalendar('selectionMode');
      }
   }

   specialDates(arg?: Array<any>) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('specialDates', arg);
      } else {
          return this.host.jqxCalendar('specialDates');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('theme', arg);
      } else {
          return this.host.jqxCalendar('theme');
      }
   }

   titleHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('titleHeight', arg);
      } else {
          return this.host.jqxCalendar('titleHeight');
      }
   }

   titleFormat(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('titleFormat', arg);
      } else {
          return this.host.jqxCalendar('titleFormat');
      }
   }

   todayString(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('todayString', arg);
      } else {
          return this.host.jqxCalendar('todayString');
      }
   }

   value(arg?: Date) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('value', arg);
      } else {
          return this.host.jqxCalendar('value');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('width', arg);
      } else {
          return this.host.jqxCalendar('width');
      }
   }


   // jqxCalendarComponent functions
   clear(): void {
      this.host.jqxCalendar('clear');
   }

   destroy(): void {
      this.host.jqxCalendar('destroy');
   }

   focus(): void {
      this.host.jqxCalendar('focus');
   }

   addSpecialDate(date?: any, tooltip?: any, text?: any): void {
      this.host.jqxCalendar('addSpecialDate', date, tooltip, text);
   }

   getMinDate(): any {
      return this.host.jqxCalendar('getMinDate');
   }

   getMaxDate(): any {
      return this.host.jqxCalendar('getMaxDate');
   }

   getDate(): any {
      return this.host.jqxCalendar('getDate');
   }

   getRange(): any {
      return this.host.jqxCalendar('getRange');
   }

   navigateForward(months: number): void {
      this.host.jqxCalendar('navigateForward', months);
   }

   navigateBackward(months: number): void {
      this.host.jqxCalendar('navigateBackward', months);
   }

   render(): void {
      this.host.jqxCalendar('render');
   }

   refresh(): void {
      this.host.jqxCalendar('refresh');
   }

   setMinDate(date: any): void {
      this.host.jqxCalendar('setMinDate', date);
   }

   setMaxDate(date: any): void {
      this.host.jqxCalendar('setMaxDate', date);
   }

   setDate(date: any): void {
      this.host.jqxCalendar('setDate', date);
   }

   setRange(date: any, date2: any): void {
      this.host.jqxCalendar('setRange', date, date2);
   }

   today(): void {
      this.host.jqxCalendar('today');
   }

   val(value?: any, value2?: any): any {
      if (value !== undefined) {
         return this.host.jqxCalendar("val", value, value2);
      } else {
         return this.host.jqxCalendar("val");
      }
   };


   // jqxCalendarComponent events
   @Output() onBackButtonClick = new EventEmitter();
   @Output() onChange = new EventEmitter();
   @Output() onNextButtonClick = new EventEmitter();
   @Output() onViewChange = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('backButtonClick', (eventData: any) => { this.onBackButtonClick.emit(eventData); });
      this.host.on('change', (eventData: any) => { this.onChange.emit(eventData); this.onChangeCallback(this.host.val()); });
      this.host.on('nextButtonClick', (eventData: any) => { this.onNextButtonClick.emit(eventData); });
      this.host.on('viewChange', (eventData: any) => { this.onViewChange.emit(eventData); });
   }

} //jqxCalendarComponent

// jqwidgets-ver5.2.0/jqwidgets-react/react_jqxcalendar.js
/*
jQWidgets v5.2.0 (2017-Sep)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxCalendar extends React.Component {
    componentDidMount() {
        let options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        let properties = ['backText','columnHeaderHeight','clearString','culture','dayNameFormat','disabled','enableWeekend','enableViews','enableOtherMonthDays','enableFastNavigation','enableHover','enableAutoNavigation','enableTooltips','forwardText','firstDayOfWeek','height','min','max','navigationDelay','rowHeaderWidth','readOnly','restrictedDates','rtl','stepMonths','showWeekNumbers','showDayNames','showOtherMonthDays','showFooter','selectionMode','specialDates','theme','titleHeight','titleFormat','todayString','value','width'];
        let options = {};
        for(let item in this.props) {
              if(item === 'settings') {
                  for(let itemTwo in this.props[item]) {
                      options[itemTwo] = this.props[item][itemTwo];
                      }
                } else {
                      if(properties.indexOf(item) !== -1) {
                        options[item] = this.props[item];
                      }
                }
          }
          return options;
      };
    createComponent(options) {
        if(!this.style) {
              for (let style in this.props.style) {
                  JQXLite(this.componentSelector).css(style, this.props.style[style]);
              }
        }
        if(this.props.className !== undefined) {
            let classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
              JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxCalendar(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxCalendar('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxCalendar(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    backText(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('backText', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('backText');
        }
    };
    columnHeaderHeight(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('columnHeaderHeight', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('columnHeaderHeight');
        }
    };
    clearString(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('clearString', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('clearString');
        }
    };
    culture(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('culture', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('culture');
        }
    };
    dayNameFormat(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('dayNameFormat', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('dayNameFormat');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('disabled');
        }
    };
    enableWeekend(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableWeekend', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableWeekend');
        }
    };
    enableViews(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableViews', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableViews');
        }
    };
    enableOtherMonthDays(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableOtherMonthDays', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableOtherMonthDays');
        }
    };
    enableFastNavigation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableFastNavigation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableFastNavigation');
        }
    };
    enableHover(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableHover', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableHover');
        }
    };
    enableAutoNavigation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableAutoNavigation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableAutoNavigation');
        }
    };
    enableTooltips(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('enableTooltips', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('enableTooltips');
        }
    };
    forwardText(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('forwardText', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('forwardText');
        }
    };
    firstDayOfWeek(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('firstDayOfWeek', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('firstDayOfWeek');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('height');
        }
    };
    min(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('min', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('min');
        }
    };
    max(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('max', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('max');
        }
    };
    navigationDelay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('navigationDelay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('navigationDelay');
        }
    };
    rowHeaderWidth(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('rowHeaderWidth', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('rowHeaderWidth');
        }
    };
    readOnly(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('readOnly', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('readOnly');
        }
    };
    restrictedDates(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('restrictedDates', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('restrictedDates');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('rtl');
        }
    };
    stepMonths(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('stepMonths', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('stepMonths');
        }
    };
    showWeekNumbers(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('showWeekNumbers', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('showWeekNumbers');
        }
    };
    showDayNames(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('showDayNames', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('showDayNames');
        }
    };
    showOtherMonthDays(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('showOtherMonthDays', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('showOtherMonthDays');
        }
    };
    showFooter(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('showFooter', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('showFooter');
        }
    };
    selectionMode(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('selectionMode', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('selectionMode');
        }
    };
    specialDates(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('specialDates', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('specialDates');
        }
    };
    theme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('theme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('theme');
        }
    };
    titleHeight(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('titleHeight', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('titleHeight');
        }
    };
    titleFormat(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('titleFormat', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('titleFormat');
        }
    };
    todayString(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('todayString', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('todayString');
        }
    };
    value(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('value', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('value');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('width');
        }
    };
    clear() {
        JQXLite(this.componentSelector).jqxCalendar('clear');  
    };
    destroy() {
        JQXLite(this.componentSelector).jqxCalendar('destroy');  
    };
    focus() {
        JQXLite(this.componentSelector).jqxCalendar('focus');  
    };
    addSpecialDate(date, tooltip, text) {
        JQXLite(this.componentSelector).jqxCalendar('addSpecialDate', date, tooltip, text);  
    };
    getMinDate() {
        return JQXLite(this.componentSelector).jqxCalendar('getMinDate');  
    };
    getMaxDate() {
        return JQXLite(this.componentSelector).jqxCalendar('getMaxDate');  
    };
    getDate() {
        return JQXLite(this.componentSelector).jqxCalendar('getDate');  
    };
    getRange() {
        return JQXLite(this.componentSelector).jqxCalendar('getRange');  
    };
    navigateForward(months) {
        JQXLite(this.componentSelector).jqxCalendar('navigateForward', months);  
    };
    navigateBackward(months) {
        JQXLite(this.componentSelector).jqxCalendar('navigateBackward', months);  
    };
    performRender() {
        JQXLite(this.componentSelector).jqxCalendar('render');
    };
    refresh() {
        JQXLite(this.componentSelector).jqxCalendar('refresh');  
    };
    setMinDate(date) {
        JQXLite(this.componentSelector).jqxCalendar('setMinDate', date);  
    };
    setMaxDate(date) {
        JQXLite(this.componentSelector).jqxCalendar('setMaxDate', date);  
    };
    setDate(date) {
        JQXLite(this.componentSelector).jqxCalendar('setDate', date);  
    };
    setRange(date, date2) {
        JQXLite(this.componentSelector).jqxCalendar('setRange', date, date2);  
    };
    today() {
        JQXLite(this.componentSelector).jqxCalendar('today');  
    };
    val(value, value2) {
        if (value !== undefined) {
            JQXLite(this.componentSelector).jqxCalendar('val',  value, value2)
        } else {
            return JQXLite(this.componentSelector).jqxCalendar('val');
        }
    };

    render() {
        let id = 'jqxCalendar' + JQXLite.generateID();
        this.componentSelector = '#' + id;
        return (
            <div id={id}>{this.props.value}{this.props.children}</div>
        )
    };
};
