// jqwidgets-ver5.2.0/jqwidgets-ts/angular_jqxknob.ts
/*
jQWidgets v5.2.0 (2017-Sep)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges, ChangeDetectionStrategy } from '@angular/core';
declare let JQXLite: any;

@Component({
    selector: 'jqxKnob',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxKnobComponent implements OnChanges
{
   @Input('allowValueChangeOnClick') attrAllowValueChangeOnClick: any;
   @Input('allowValueChangeOnDrag') attrAllowValueChangeOnDrag: any;
   @Input('allowValueChangeOnMouseWheel') attrAllowValueChangeOnMouseWheel: any;
   @Input('changing') attrChanging: any;
   @Input('dragEndAngle') attrDragEndAngle: any;
   @Input('dragStartAngle') attrDragStartAngle: any;
   @Input('disabled') attrDisabled: any;
   @Input('dial') attrDial: any;
   @Input('endAngle') attrEndAngle: any;
   @Input('labels') attrLabels: any;
   @Input('marks') attrMarks: any;
   @Input('min') attrMin: any;
   @Input('max') attrMax: any;
   @Input('progressBar') attrProgressBar: any;
   @Input('pointer') attrPointer: any;
   @Input('pointerGrabAction') attrPointerGrabAction: any;
   @Input('rotation') attrRotation: any;
   @Input('startAngle') attrStartAngle: any;
   @Input('spinner') attrSpinner: any;
   @Input('style') attrStyle: any;
   @Input('step') attrStep: any;
   @Input('snapToStep') attrSnapToStep: any;
   @Input('value') attrValue: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['allowValueChangeOnClick','allowValueChangeOnDrag','allowValueChangeOnMouseWheel','changing','dragEndAngle','dragStartAngle','disabled','dial','endAngle','height','labels','marks','min','max','progressBar','pointer','pointerGrabAction','rotation','startAngle','spinner','style','step','snapToStep','value','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxKnob;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
      JQXLite(window).resize(() => {
          this.__updateRect__();
      });
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxKnob(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxKnob(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxKnob(this.properties[i])) {
                  this.host.jqxKnob(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   moveClasses(parentEl: HTMLElement, childEl: HTMLElement): void {
      let classes: any = parentEl.classList;
      childEl.classList.add(...classes);
      parentEl.className = '';
   }

   moveStyles(parentEl: HTMLElement, childEl: HTMLElement): void {
      let style = parentEl.style.cssText;
      childEl.style.cssText = style
      parentEl.style.cssText = '';
   }

   createComponent(options?: any): void {
      if (options) {
         JQXLite.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = JQXLite(this.elementRef.nativeElement.firstChild);

      this.moveClasses(this.elementRef.nativeElement, this.host[0]);
      this.moveStyles(this.elementRef.nativeElement, this.host[0]);

      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxKnob', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxKnob('setOptions', options);
   }

   // jqxKnobComponent properties
   allowValueChangeOnClick(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('allowValueChangeOnClick', arg);
      } else {
          return this.host.jqxKnob('allowValueChangeOnClick');
      }
   }

   allowValueChangeOnDrag(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('allowValueChangeOnDrag', arg);
      } else {
          return this.host.jqxKnob('allowValueChangeOnDrag');
      }
   }

   allowValueChangeOnMouseWheel(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('allowValueChangeOnMouseWheel', arg);
      } else {
          return this.host.jqxKnob('allowValueChangeOnMouseWheel');
      }
   }

   changing(arg?: (oldValue: String | Number, newValue: String | Number) => Boolean) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('changing', arg);
      } else {
          return this.host.jqxKnob('changing');
      }
   }

   dragEndAngle(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('dragEndAngle', arg);
      } else {
          return this.host.jqxKnob('dragEndAngle');
      }
   }

   dragStartAngle(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('dragStartAngle', arg);
      } else {
          return this.host.jqxKnob('dragStartAngle');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('disabled', arg);
      } else {
          return this.host.jqxKnob('disabled');
      }
   }

   dial(arg?: jqwidgets.KnobDial) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('dial', arg);
      } else {
          return this.host.jqxKnob('dial');
      }
   }

   endAngle(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('endAngle', arg);
      } else {
          return this.host.jqxKnob('endAngle');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('height', arg);
      } else {
          return this.host.jqxKnob('height');
      }
   }

   labels(arg?: jqwidgets.KnobLabels) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('labels', arg);
      } else {
          return this.host.jqxKnob('labels');
      }
   }

   marks(arg?: jqwidgets.KnobMarks) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('marks', arg);
      } else {
          return this.host.jqxKnob('marks');
      }
   }

   min(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('min', arg);
      } else {
          return this.host.jqxKnob('min');
      }
   }

   max(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('max', arg);
      } else {
          return this.host.jqxKnob('max');
      }
   }

   progressBar(arg?: jqwidgets.KnobProgressBar) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('progressBar', arg);
      } else {
          return this.host.jqxKnob('progressBar');
      }
   }

   pointer(arg?: jqwidgets.KnobPointer) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('pointer', arg);
      } else {
          return this.host.jqxKnob('pointer');
      }
   }

   pointerGrabAction(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('pointerGrabAction', arg);
      } else {
          return this.host.jqxKnob('pointerGrabAction');
      }
   }

   rotation(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('rotation', arg);
      } else {
          return this.host.jqxKnob('rotation');
      }
   }

   startAngle(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('startAngle', arg);
      } else {
          return this.host.jqxKnob('startAngle');
      }
   }

   spinner(arg?: jqwidgets.KnobSpinner) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('spinner', arg);
      } else {
          return this.host.jqxKnob('spinner');
      }
   }

   style(arg?: jqwidgets.KnobStyle) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('style', arg);
      } else {
          return this.host.jqxKnob('style');
      }
   }

   step(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('step', arg);
      } else {
          return this.host.jqxKnob('step');
      }
   }

   snapToStep(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('snapToStep', arg);
      } else {
          return this.host.jqxKnob('snapToStep');
      }
   }

   value(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('value', arg);
      } else {
          return this.host.jqxKnob('value');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxKnob('width', arg);
      } else {
          return this.host.jqxKnob('width');
      }
   }


   // jqxKnobComponent functions
   destroy(): void {
      this.host.jqxKnob('destroy');
   }

   val(value?: String | Number): any {
      if (value !== undefined) {
         return this.host.jqxKnob("val", value);
      } else {
         return this.host.jqxKnob("val");
      }
   };


   // jqxKnobComponent events
   @Output() onChange = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('change', (eventData: any) => { this.onChange.emit(eventData); });
   }

} //jqxKnobComponent

// jqwidgets-ver5.2.0/jqwidgets-react/react_jqxknob.js
/*
jQWidgets v5.2.0 (2017-Sep)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

const JQXLite = window.JQXLite;

export const jqx = window.jqx;

export default class JqxKnob extends React.Component {
    componentDidMount() {
        let options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        let properties = ['allowValueChangeOnClick','allowValueChangeOnDrag','allowValueChangeOnMouseWheel','changing','dragEndAngle','dragStartAngle','disabled','dial','endAngle','height','labels','marks','min','max','progressBar','pointer','pointerGrabAction','rotation','startAngle','spinner','style','step','snapToStep','value','width'];
        let options = {};
        for(let item in this.props) {
              if(item === 'settings') {
                  for(let itemTwo in this.props[item]) {
                      options[itemTwo] = this.props[item][itemTwo];
                      }
                } else {
                      if(properties.indexOf(item) !== -1) {
                        options[item] = this.props[item];
                      }
                }
          }
          return options;
      };
    createComponent(options) {
        if(!this.style) {
              for (let style in this.props.style) {
                  JQXLite(this.componentSelector).css(style, this.props.style[style]);
              }
        }
        if(this.props.className !== undefined) {
            let classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
              JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxKnob(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxKnob('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxKnob(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    allowValueChangeOnClick(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('allowValueChangeOnClick', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('allowValueChangeOnClick');
        }
    };
    allowValueChangeOnDrag(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('allowValueChangeOnDrag', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('allowValueChangeOnDrag');
        }
    };
    allowValueChangeOnMouseWheel(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('allowValueChangeOnMouseWheel', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('allowValueChangeOnMouseWheel');
        }
    };
    changing(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('changing', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('changing');
        }
    };
    dragEndAngle(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('dragEndAngle', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('dragEndAngle');
        }
    };
    dragStartAngle(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('dragStartAngle', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('dragStartAngle');
        }
    };
    disabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('disabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('disabled');
        }
    };
    dial(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('dial', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('dial');
        }
    };
    endAngle(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('endAngle', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('endAngle');
        }
    };
    height(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('height', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('height');
        }
    };
    labels(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('labels', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('labels');
        }
    };
    marks(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('marks', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('marks');
        }
    };
    min(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('min', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('min');
        }
    };
    max(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('max', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('max');
        }
    };
    progressBar(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('progressBar', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('progressBar');
        }
    };
    pointer(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('pointer', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('pointer');
        }
    };
    pointerGrabAction(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('pointerGrabAction', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('pointerGrabAction');
        }
    };
    rotation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('rotation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('rotation');
        }
    };
    startAngle(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('startAngle', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('startAngle');
        }
    };
    spinner(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('spinner', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('spinner');
        }
    };
    style(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('style', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('style');
        }
    };
    step(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('step', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('step');
        }
    };
    snapToStep(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('snapToStep', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('snapToStep');
        }
    };
    value(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('value', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('value');
        }
    };
    width(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('width', arg)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('width');
        }
    };
    destroy() {
        JQXLite(this.componentSelector).jqxKnob('destroy');  
    };
    val(value) {
        if (value !== undefined) {
            JQXLite(this.componentSelector).jqxKnob('val',  value)
        } else {
            return JQXLite(this.componentSelector).jqxKnob('val');
        }
    };

    render() {
        let id = 'jqxKnob' + JQXLite.generateID();
        this.componentSelector = '#' + id;
        return (
            <div id={id}>{this.props.value}{this.props.children}</div>
        )
    };
};
